### ISSUE TITLE
[Server] 파일 이름을 pascal case 로 하는 이유가 있나요?

### ISSUE THREAD

**Issue by insanehong** [boostcamp-2020/Project04-B-Whale#64]
file name 을 pascal case 로 하시는 이유가 궁금하네요

추가로 
https://github.com/boostcamp-2020/Project04-B-Whale/tree/master/server/src/common/middleware

여기 파일들은 Pascal case 와 camel case 가 공존하는데 실수인가요?

**Comment by youngxpepp** [comment]
클래스와 함수 파일을 구분하기 위해서 파스칼과 카멜을 혼합해서 사용했습니다.
일반적으로 파일 형식을 어떻게 해결하고 있는지 여쭤도 될까요?
감사합니다!

**Comment by insanehong** [comment]
camel case 를 주로 사용하고 있고 여러 이유가 있는데 

아래의 글처럼 식으로 많은 논의가 있는데 일반적으로 파일명을 대분자로 시작하거나 대문자로 만드는경우는 특별한 목적이 없다면 잘 안하는것 같네요

https://unix.stackexchange.com/questions/239295/is-it-considered-a-best-practice-to-not-use-capital-letters-in-file-naming

**Comment by youngxpepp** [comment]
@insanehong 멘토님 조언 감사합니다!
유명 라이브러리들의 파일 네이밍은 어떨까 하고 찾아봤습니다. 현재 프로젝트가 라이브러리와는 다른 성격의 프로젝트이기 때문에, 차이점이 있을 수 있겠지만 너무나도 다양한 네이밍 전략을 사용하고 있는걸 알 수 있었습니다.
멘토님 말씀처럼 Pascal과 Camel이 공존하고 있는데, 관련 부분은 수정되어야 할 것 같습니다. 네이밍 전략은 다른 팀원과의 중요한 소통이 될 수 있기 때문에 내일 회의를 통해서 다시 결정하도록 하겠습니다.

https://github.com/petkaantonov/bluebird/tree/master/src
https://github.com/lodash/lodash
https://github.com/eslint/eslint/tree/master/lib
https://github.com/moment/moment/tree/develop/src/lib
https://github.com/expressjs/express/tree/master/lib
https://github.com/koajs/koa/tree/master/lib
https://github.com/facebook/react/tree/master/packages/react/src
https://github.com/nestjs/nest/tree/master/packages/core
https://github.com/typeorm/typeorm/tree/master/src
https://github.com/typestack/class-validator/tree/develop/src
https://github.com/microsoft/TypeScript/tree/master/src
