### ISSUE TITLE
[Server] AbstractService Class 정의에 대해 문의 합니다.

### ISSUE THREAD

**Issue by insanehong** [boostcamp-2020/Project04-B-Whale#65]
제가 볼때 이 Class 는 Abstract 과 아무 관련이 없어보이는데요.
extends parent 용으로 사용할거면 Abstract 보다 base 가 더 낫지 않을가요... 

```js
export class AbstractService {
    constructor() {
        this.activityRepository = getRepository(Activity);
        this.boardRepository = getRepository(Board);
        this.cardRepository = getRepository(Card);
        this.commentRepository = getRepository(Comment);
        this.invitationRepository = getRepository(Invitation);
        this.listRepository = getRepository(List);
        this.userRepository = getRepository(User);
    }
}
```

Refer: https://github.com/boostcamp-2020/Project04-B-Whale/blob/master/server/src/service/AbstractService.js

**Comment by youngxpepp** [comment]
"해당 클래스의 인스턴스를 만들 일은 없지 않을까?" 라는 생각에서부터 Abstract 라는 네이밍을 했습니다.
Java와 다르게 abstract 키워드가 없어서 네이밍으로 대체했는데, Base는 생각도 못했습니다. 더 직관적이라고 생각합니다!
리뷰 감사합니다👏

**Comment by insanehong** [comment]
사용하는것을 보닌 implements 가 아닌 extends 쓰고 있길래 궁금했습니다.
